### ISSUE TITLE
[Spell] Slam

### ISSUE THREAD

**Issue by PN-Cryptid** [ProjectNelth/BugTracker#348] opened 2021-05-15 14:07 UTC
Description:
Warrior spell 1464, producing spell 50782.
Current behaviour:

Slam will, at random, consume bloodsurge without triggering any damage.
![image](https://user-images.githubusercontent.com/58305537/118364151-3c203480-b565-11eb-8fc2-11afc2de263f.png)
![image](https://user-images.githubusercontent.com/58305537/118364435-6cb49e00-b566-11eb-984a-9ecc3d66762d.png)

Expected behaviour:
Slam should never "vanish" from the fight.

**Comment by therealsmf** [comment] 2021-09-09 03:38
been hitting a dummy for half an hour, none of my procs disappeared or didnt deal damage. since you have no timestamps on the screenshots, im assuming the proc just faded and you cancelled the natural cast time of the slam (?) marking this as invalid until theres clear video evidence of a successful slam instantcast not dealing damage.

**Comment by therealsmf** [comment] 2021-09-09 03:52
actually, only now that i'm playing around with slam itself i noticed you can "cancel" slam by running out of range as soon as the cast is about to finish. this is the only way it does not show up in the combat log or do any damage (see video). 

https://www.youtube.com/watch?v=FITV9cSKMXA

since the instantcast would be instantly calculated in melee range giving no leeway, it would be impossible to replicate this with a proc. from what i can tell you were at the "end" part of hitting the dummy, and your proc either faded naturally, or somehow you managed to run out of range with an instantcast melee range spell (ping?)

would love to see this in action either way, im afraid i cant realistically reproduce this even if i wanted to.

**Comment by therealsmf** [comment] 2021-09-09 17:20
![image](https://user-images.githubusercontent.com/66882878/132732738-9cbf4c28-614a-4aaf-a769-36c4c10ac819.png)

**Closed by therealsmf** 2021-09-09 17:20 UTC
Labels: invalid
